# Generated by Django 5.0.1 on 2024-03-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_auction_category_bids_auction_category_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                choices=[
                    ("Electronics", "Electronics"),
                    ("Clothing", "Clothing"),
                    ("Home & Garden", "Home & Garden"),
                    ("Toys & Games", "Toys & Games"),
                    ("Books & Magazines", "Books & Magazines"),
                    ("Sports & Outdoors", "Sports & Outdoors"),
                    ("Health & Beauty", "Health & Beauty"),
                    ("Collectibles", "Collectibles"),
                    ("Automotive", "Automotive"),
                    ("Miscellaneous", "Miscellaneous"),
                ],
                max_length=30,
            ),
        ),
    ]
