# Generated by Django 5.0.1 on 2024-03-25 00:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0004_auction_creator_auction_is_open_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="highest_bid",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
